config/routes.rb
Example::Application.routes.draw do  
  get "omniauth_callbacks/vkontakte"

get "posts/search/" 	
  resources :posts do
    resources :vote, :only => [:update] do
      delete 'clear'
    end
  end

  
  devise_for :users
  root :to => "posts#index"

 devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :only => [:index, :destroy]
  root :to => 'users#index'

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post
  has_many :users_votes
  has_many :users, :through => :users_votes
end

app/controllers/vote_controller.rb
class VoteController < ApplicationController
	
  load_and_authorize_resource
	
  def update
	  post = Post.find(params[:post_id])
    vote = post.vote
      
    vote.score += 1 if params[:vote][:score] == "Up" 
    vote.score -= 1 if params[:vote][:score] == "Down"
    vote.users << current_user
    vote.save

    flash[:notice] = "You vote counted!"
    redirect_to post_path(post)	
	end

	def clear
    post = Post.find(params[:post_id])
    post.vote.update_attributes(:score => 0)
    
    flash[:notice] = "Clear!" 
    redirect_to post_path(post)
	end

  rescue_from CanCan::AccessDenied do |exception|
    flash[:notice] = "ushze vce" 
    redirect_to post_path(Post.find(params[:post_id]))
  end

end

app/helpers/vote_helper.rb
module VoteHelper
end

app/views/vote/_update.html.erb
<% if can? :update, Vote %>
 <%= form_for [@post, @post.vote] do |f| %>
 <div id ="oo"><%= f.label :score, "+"%>
  <%= f.radio_button :score, "Up" %>
  <%= f.label :score, "-"%>
  <%= f.radio_button :score, "Down" %>
</div>
  <br clear="all"/>
  <%= f.submit "Проголосовать" %>

 <% end %>
<% end %>

<% if can? :clear, Vote %>
 <%= link_to 'clear', post_vote_clear_path(@post, @post.vote), method: :delete %>
<% end %>